insta_data = [
    {"name": "Instagram", "followers": 687, "description": "Social Media Platform", "country": "United States"},
    {"name": "Cristiano Ronaldo", "followers": 652, "description": "Footballer", "country": "Portugal"},
    {"name": "Lionel Messi", "followers": 505, "description": "Footballer", "country": "Argentina"},
    {"name": "Selena Gomez", "followers": 421, "description": "Musician and Actress", "country": "United States"},
    {"name": "Dwayne Johnson", "followers": 394, "description": "Actor and Wrestler", "country": "United States"},
    {"name": "Kylie Jenner", "followers": 394, "description": "Media Personality", "country": "United States"},
    {"name": "Ariana Grande", "followers": 376, "description": "Musician and Actress", "country": "United States"},
    {"name": "Kim Kardashian", "followers": 357, "description": "Media Personality", "country": "United States"},
    {"name": "Beyoncé", "followers": 312, "description": "Musician and Actress", "country": "United States"},
    {"name": "Khloé Kardashian", "followers": 303, "description": "Media Personality", "country": "United States"},
    {"name": "Nike", "followers": 301, "description": "Sportswear Brand", "country": "United States"},
    {"name": "Justin Bieber", "followers": 294, "description": "Musician", "country": "Canada"},
    {"name": "Kendall Jenner", "followers": 288, "description": "Media Personality", "country": "United States"},
    {"name": "Taylor Swift", "followers": 282, "description": "Musician", "country": "United States"},
    {"name": "National Geographic", "followers": 279, "description": "Magazine", "country": "United States"},
    {"name": "Virat Kohli", "followers": 271, "description": "Cricketer", "country": "India"},
    {"name": "Jennifer Lopez", "followers": 249, "description": "Musician and Actress", "country": "United States"},
    {"name": "Neymar Jr.", "followers": 229, "description": "Footballer", "country": "Brazil"},
    {"name": "Nicki Minaj", "followers": 226, "description": "Musician", "country": "United States"},
    {"name": "Kourtney Kardashian", "followers": 219, "description": "Media Personality", "country": "United States"},
    {"name": "Miley Cyrus", "followers": 213, "description": "Musician and Actress", "country": "United States"},
    {"name": "Katy Perry", "followers": 204, "description": "Musician", "country": "United States"},
    {"name": "Zendaya", "followers": 179, "description": "Actress and Singer", "country": "United States"},
    {"name": "Kevin Hart", "followers": 177, "description": "Comedian and Actor", "country": "United States"},
    {"name": "Real Madrid", "followers": 173, "description": "Football Club", "country": "Spain"},
    {"name": "Cardi B", "followers": 164, "description": "Musician and Actress", "country": "United States"},
    {"name": "LeBron James", "followers": 159, "description": "Basketball Player", "country": "United States"},
    {"name": "Demi Lovato", "followers": 153, "description": "Musician and Actress", "country": "United States"},
    {"name": "Rihanna", "followers": 149, "description": "Musician", "country": "Barbados"},
    {"name": "Chris Brown", "followers": 144, "description": "Musician", "country": "United States"},
    {"name": "Drake", "followers": 143, "description": "Musician", "country": "Canada"},
    {"name": "Ellen DeGeneres", "followers": 136, "description": "Comedian and TV Host", "country": "United States"},
    {"name": "FC Barcelona", "followers": 136, "description": "Football Club", "country": "Spain"},
    {"name": "Billie Eilish", "followers": 124, "description": "Musician", "country": "United States"},
    {"name": "Kylian Mbappé", "followers": 123, "description": "Footballer", "country": "France"},
    {"name": "UEFA Champions League", "followers": 120, "description": "Football Competition", "country": "Europe"},
    {"name": "Gal Gadot", "followers": 108, "description": "Actress", "country": "Israel"},
    {"name": "Lisa", "followers": 105, "description": "Musician", "country": "Thailand"},
    {"name": "Vin Diesel", "followers": 103, "description": "Actor", "country": "United States"},
    {"name": "NASA", "followers": 96.8, "description": "Space Agency", "country": "United States"},
    {"name": "Narendra Modi", "followers": 96.3, "description": "Prime Minister", "country": "India"},
    {"name": "Shraddha Kapoor", "followers": 93.8, "description": "Actress", "country": "India"},
    {"name": "Alia Bhatt", "followers": 86.4, "description": "Actress", "country": "India"},
    {"name": "Rosé", "followers": 83.9, "description": "Musician", "country": "South Korea"},
    {"name": "Jisoo", "followers": 79.4, "description": "Musician", "country": "South Korea"},
    {"name": "BTS Official", "followers": 76.7, "description": "Music Group", "country": "South Korea"},
    {"name": "Karol G", "followers": 70.8, "description": "Musician", "country": "Colombia"},
    {"name": "Anushka Sharma", "followers": 69.7, "description": "Actress", "country": "India"},
    {"name": "V (BTS)", "followers": 68.1, "description": "Musician", "country": "South Korea"}
]
